services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: passwort
    ports:
      - "5441:5431"
      - "5442:5432"
    volumes:
      - "./postgres/backups:/var/lib/postgresql/backups"

  php:
    build:
      context: ./php
    ports:
      - '9001:9000'
    volumes:
      - "./app:/var/www/symfony_docker"
    depends_on:
      - postgres

  nginx:
    image: nginx:stable-alpine
    ports:
      - '8081:80'
    volumes:
      - ./app:/var/www/symfony_docker
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - postgres